package ru.morgan.exelparser.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import java.util.HashSet;
import java.util.Set;

/*
create table if not exists discipline(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    type_of_sport_id int,
    age_group_ids integer[]
);
 */

@Data
@Entity
@RequiredArgsConstructor
public class Discipline {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String title;
    private int typeOfSportId;
    private Set<Integer> ageGroupIds = new HashSet<>();

    public void addAgeGroup(AgeGroup ageGroup){
        ageGroupIds.add(ageGroup.getId());
    }
}
