package ru.morgan.exelparser.models;

/*
create table if not exists participant(
    id int GENERATED BY DEFAULT AS IDENTITY,
    name text not null,
    middle_name text,
    lastname text not null,
    birthday date not null,
    subject_ids integer[],
    qualification_ids integer[]
);
 */

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

@Data
@Entity
@RequiredArgsConstructor
public class Participant {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String name;
    private String middleName;
    private String lastname;
    private LocalDate birthday;
    private Set<Integer> subjectIds = new HashSet<>();
    private Set<Integer> qualificationIds = new HashSet<>();

    public void addSubject(Subject subject){
        subjectIds.add(subject.getId());
    }
}
