package ru.morgan.exelparser.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import lombok.NoArgsConstructor;

/*
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text,
    ogrn int,
    index int,
    address text,
    url text,
    s float,
    d float,

    logoId bigint,
    photoId bigint
 */

@Data
@Entity
@NoArgsConstructor
public class School {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    private String name;
    private long ogrn;
    private int index;
    private String address;
    private String url;
    private float s;
    private float d;

    private String subject;

    private long logoId;
    private long PhotoId;
}
