package ru.morgan.exelparser.models;

/*
create table if not exists sport_school(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    address text,
    subject_id int,
    participant_ids integer[]
);
 */

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.HashSet;
import java.util.Set;

@Data
@Entity
@NoArgsConstructor
public class SportSchool {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String title;
    private String address;
    private int subjectId;
    private Set<Integer> participantIds = new HashSet<>();

    public void addParticipant(Participant participant){
        if(participantIds == null){
            participantIds = new HashSet<>();
        }
        participantIds.add(participant.getId());
    }

    public void addParticipantId(int participantId){
        if(participantIds == null){
            participantIds = new HashSet<>();
        }
        participantIds.add(participantId);
    }
}
