package ru.morgan.exelparser.models;

/*
create table if not exists subject(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    type_od_sport_ids integer[],
    participant_ids integer[]
);
 */

import jakarta.persistence.*;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import java.util.HashSet;
import java.util.Set;

@Data
@Entity
@RequiredArgsConstructor
public class Subject {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String title;
    private String iso;
    @Enumerated(EnumType.STRING)
    private FederalDistrict federalDistrict;
    private Set<Integer> sportSchoolIds = new HashSet<>();
    private Set<Integer> baseSportIds = new HashSet<>();

    public void addSportSchool(SportSchool sportSchool){
        if(sportSchoolIds == null){
            sportSchoolIds = new HashSet<>();
        }
        sportSchoolIds.add(sportSchool.getId());
    }

    public void addSportSchoolId(int sportSchoolId){
        if(sportSchoolIds == null){
            sportSchoolIds = new HashSet<>();
        }
        sportSchoolIds.add(sportSchoolId);
    }

    public void addBaseSport(BaseSport baseSport){
        baseSportIds.add(baseSport.getId());
    }

    public void addBaseSportId(int baseSportId){
        baseSportIds.add(baseSportId);
    }
}
