package ru.morgan.exelparser.models;

/*
create table if not exists subject(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    type_od_sport_ids integer[],
    participant_ids integer[]
);
 */

import jakarta.persistence.*;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import java.util.HashSet;
import java.util.Set;

@Data
@Entity
@RequiredArgsConstructor
public class Subject {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String title;
    @Enumerated(EnumType.STRING)
    private FederalDistrict federalDistrict;
    private Set<Integer> typeOfSportIds = new HashSet<>();
    private Set<Integer> participantIds = new HashSet<>();

    public void addTypeOfSport(TypeOfSport typeOfSport){
        typeOfSportIds.add(typeOfSport.getId());
    }

    public void addParticipant(Participant participant){
        participantIds.add(participant.getId());
    }
}
